---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzafrontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pizzafrontend
    spec:
      containers:
      - name: pizzafrontend
        # image: docker-username/image-name:version
        image: simaoppcastro/pizzafrontend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: backendUrl
          value: http://pizzabackend
        # good practice to add resources limits
        resources:
          limits:
            memory: 256Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
  selector:
    matchLabels:
      app: pizzafrontend
---
apiVersion: v1
kind: Service
metadata:
  name: pizzafrontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: pizzafrontend

# -> kubectl apply -f backend-deploy.yml
# -> kubectl get pods